apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: ghcr.io/zarayach/microservices-pfm/authorizationserver:1.1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: "host.docker.internal"  # Replace with DB server address
            - name: DB_PORT
              value: "3307"
            - name: DB_NAME
              value: "microservice_pfm_auth_server"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 180
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 180

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
