apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/zarayach/microservices-pfm/payment:1.1.4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: host.docker.internal  # Replace with DB server address
            - name: DB_PORT
              value: "3307"
            - name: DB_NAME
              value: "microservice_pfm_payment"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: "OAUTH2_JWT_ISSUER_URI"
              value: "https://pfmtimemanagementbackend.eastus.cloudapp.azure.com"
            - name: "OAUTH2_JWK_SET_URI"
              value: "https://pfmtimemanagementbackend.eastus.cloudapp.azure.com/oauth2/jwks"
            - name: "SERVICES_ROOT_URL"
              value: "https://payment.pfmmicroservices.local"
            - name: "SERVICES_EVENT_URL"
              value: "http://event-service"
            - name: "SERVICES_RESERVATION_URL"
              value: "https://reservation.pfmmicroservices.local"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80


---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
